DRIVER 'org.apache.derby.jdbc.ClientDriver';
connect 'jdbc:derby://localhost:1527/JavaTunesDB' USER 'guest' PASSWORD 'password';

DROP TABLE Item;

CREATE TABLE Item
(
   ITEM_ID     BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
   Title       VARCHAR(40),
   Artist      VARCHAR(40),
   ReleaseDate DATE,
   ListPrice   DECIMAL(5,2),
   Price       DECIMAL(5,2),
   Version     INTEGER,
   CONSTRAINT  PK_Item  PRIMARY KEY(ITEM_ID)
);

INSERT INTO Item VALUES (DEFAULT, 'Diva', 'Annie Lennox', '1992-01-04', 17.97, 13.99,1);
INSERT INTO Item VALUES (DEFAULT, 'Dream of the Blue Turtles', 'Sting', '1985-02-05', 17.97, 14.99,1);
INSERT INTO Item VALUES (DEFAULT, 'Trouble is...', 'Kenny Wayne Shepherd Band', '1997-08-08', 17.97, 14.99,1);
INSERT INTO Item VALUES (DEFAULT, 'Lie to Me', 'Jonny Lang', '1997-08-26', 17.97, 14.99,1);
INSERT INTO Item VALUES (DEFAULT, 'Little Earthquakes', 'Tori Amos', '1992-01-18', 17.97, 14.99,1);
INSERT INTO Item VALUES (DEFAULT, 'Seal', 'Seal', '1991-08-18', 17.97, 14.99,1);
INSERT INTO Item VALUES (DEFAULT, 'Ian Moore', 'Ian Moore', '1993-12-05', 9.97, 9.97,1);
INSERT INTO Item VALUES (DEFAULT, 'So Much for the Afterglow', 'Everclear', '1997-01-19', 16.97, 13.99,1);
INSERT INTO Item VALUES (DEFAULT, 'Surfacing', 'Sarah McLachlan', '1997-12-04', 17.97, 13.99,1);
INSERT INTO Item VALUES (DEFAULT, 'Hysteria', 'Def Leppard', '1987-06-20', 17.97, 14.99,1);
INSERT INTO Item VALUES (DEFAULT, 'A Life of Saturdays', 'Dexter Freebish', '2000-12-06', 16.97, 12.99,1);
INSERT INTO Item VALUES (DEFAULT, 'Human Clay', 'Creed', '1999-10-21', 18.97, 13.28,1);
INSERT INTO Item VALUES (DEFAULT, 'My, I''m Large', 'Bobs', '1987-02-20', 11.97, 11.97,1);
INSERT INTO Item VALUES (DEFAULT, 'So', 'Peter Gabriel', '1986-10-03', 17.97, 13.99,1);
INSERT INTO Item VALUES (DEFAULT, 'Big Ones', 'Aerosmith', '1994-05-08', 18.97, 14.99,1);
INSERT INTO Item VALUES (DEFAULT, '90125', 'Yes', '1983-10-16', 11.97, 11.97,1);
INSERT INTO Item VALUES (DEFAULT, '1984', 'Van Halen', '1984-08-19', 11.97, 11.97,1);
INSERT INTO Item VALUES (DEFAULT, 'Escape', 'Journey', '1981-02-25', 11.97, 11.97,1);
INSERT INTO Item VALUES (DEFAULT, 'Greatest Hits', 'Jay and the Americans', '1966-12-05', 13.99, 9.97,1);
INSERT INTO Item VALUES (DEFAULT, 'Ray of Light', 'Madonna', '2000-12-15', 14.99, 10.97,1);
INSERT INTO Item VALUES (DEFAULT, 'Music', 'Madonna', '2002-02-27', 14.99, 11.97,1);

COMMIT;
